### ISSUE TITLE
vote through snapshot

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#10]

**Comment by twodam** [comment]
implemented by https://github.com/nance-eth/MoonDAO-app/commit/0612cff7a74ac7d9f3cd9d0f0d15e1b9e2c07a73

**Comment by jigglyjams** [comment]
need to encrypt vote

**Comment by twodam** [comment]
frontend should encrypt choice for shutter vote
* encrypt https://github.com/snapshot-labs/snapshot/blob/60e9788391c6225110823c3c728651aa3eaaa537/src/helpers/shutter.ts#L4
* interface https://github.com/snapshot-labs/snapshot/blob/60e9788391c6225110823c3c728651aa3eaaa537/src/components/ModalVote.vue#L5

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/MoonDAO-app/commit/9117abf1252675a0aaaa0766505b89d03f24554f#diff-1c6e05b22a7db0d37e91d73fdbeb6616b1262e7760cdc82f6c92b1a9e3c49c13
