### ISSUE TITLE
[Action] Add discordIds and wallets of project members

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#15]

**Comment by twodam** [comment]
https://docs.google.com/document/d/1N-NZ4fPic_WOnBGaYDd3-zzJ4JJ8tq0M2Y2wu2HmVsA/edit#heading=h.ixrjc4ns2bss

**Comment by jigglyjams** [comment]
![Image](https://github.com/nance-eth/MoonDAO-app/assets/83923290/7155504e-735a-4965-8460-bd38cf1f678d)

**Comment by jigglyjams** [comment]
move all to #12
