### ISSUE TITLE
Request to snapshot for proposal vote results is empty sometimes

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#16]
![Image](https://github.com/nance-eth/MoonDAO-app/assets/83923290/d88395dd-1fb4-4eba-8217-907a7edc745f)

for proposals in `Cancelled` or `Approved` status that have a snapshotId we will have vote results in nance db lets just use those numbers

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/MoonDAO-app/commit/3db01d179300c2bf60f8e5e43fe035127cbc2a24, with cache builtin useSWR, it's much faster to load these infos.
