### ISSUE TITLE
check address vMOONEY

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#18]
Create nextjs api function to check user vMOONEY holding amount

EDIT:
need to do check on nance-ts API as well

**Comment by twodam** [comment]
who can submit proposal based on their vMOONEY? can be implemented by guild.xyz?

**Comment by jigglyjams** [comment]
connected to nance-eth/MoonDAO-app#14

**Comment by jigglyjams** [comment]
using snapshot voting power since its hard to query directly with balanceOf when also considering delgation

**Comment by jigglyjams** [comment]
update nance-sdk to support this
https://github.com/nance-eth/nance-sdk/commit/b1ff8618abd05d4a3b85976b5c3792c98ba8c4b1

**Comment by jigglyjams** [comment]
https://github.com/nance-eth/nance-ts/commit/9f26a7a0421679f064a50a8fbae5f7b5be2304cd#diff-cce954baf8d88078636a5d95df111cf7b87bc2fb0a2a07bfe7ceb8d6ae05aa51
