### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#20]
Search box at top of Vote page

cmd-k actuated

![Image](https://github.com/nance-eth/MoonDAO-app/assets/83923290/0299aed3-587e-404d-a1c8-053fc0c899b1)

**Comment by twodam** [comment]
implemented by https://github.com/nance-eth/MoonDAO-app/commit/436f1ef8b2c3836ac655fa6504bfcaf12121f715
