### ISSUE TITLE
Sort proposal votes by vote time or power

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#22]
Like on nance.app

![Image](https://github.com/nance-eth/MoonDAO-app/assets/83923290/432817f2-bd95-47be-a9fd-938647c65f0a)

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/MoonDAO-app/commit/b610b96412b72af8d0ffa37684200a0584736bdb
