### ISSUE TITLE
add options to proposal page

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/MoonDAO-app#8]
![Image](https://github.com/nance-eth/MoonDAO-app/assets/83923290/d935c0b6-a6e8-4d5f-ac05-d1fcda844f13)

**Comment by twodam** [comment]
waiting for new signature method to edit/delete proposal

**Comment by jigglyjams** [comment]
jigglyjams to implement #19

**Comment by jigglyjams** [comment]
https://github.com/nance-eth/MoonDAO-app/commit/cacb5e04fe6db506c39bb8a8568d05dd7889657f
